halaman_forum/urls.py
from django.conf.urls import url
from .views import index, status_post

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_status', status_post, name='add_status')
]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index
from .auth import getLoginInfos, logout

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'get-login-infos/$', getLoginInfos, name='get-login-infos'),
	url(r'logout/$', logout, name='logout'),
]

halaman_utama/urls.py
from django.conf.urls import url, include
from .views import index
import response_lowongan.urls as response_lowongan

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^response-lowongan/', include(response_lowongan, namespace='response-lowongan')),
]

response_lowongan/urls.py
from django.conf.urls import url
from .views import index, add_comment

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_comment/(?P<pk>[0-9]+)/$', add_comment, name='add_comment'),
]

tugas2ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import halaman_forum.urls as halaman_forum
import halaman_utama.urls as halaman_utama
import halaman_profile.urls as halaman_profile
import response_lowongan.urls as response_lowongan

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^halaman-utama/', include(halaman_utama, namespace='halaman-utama')),
    url(r'^halaman-forum/', include(halaman_forum, namespace='halaman-forum')),
    url(r'^halaman-profile/', include(halaman_profile, namespace='halaman-profile')),
    url(r'^response-lowongan/', include(response_lowongan, namespace='response-lowongan')),
    url(r'^$', RedirectView.as_view(url='/halaman-utama/', permanent='True'), name='index'),
]

halaman_forum/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.TextField(max_length=500)
    created_date = models.DateTimeField(auto_now_add=True)

halaman_profile/models.py
from django.db import models
from django.core.validators import URLValidator

# Create your models here.
class AccountProfile(models.Model):
    company_name = models.CharField(max_length=30)
    company_about = models.CharField(max_length=500)
    company_type = models.CharField(max_length=100)
    company_web = models.TextField(validators=[URLValidator()])
    company_specialization = models.CharField(max_length=140)
    company_imgURL = models.URLField()

    def __str__(self):
    	return self.company_name

halaman_utama/models.py
from django.db import models

# Create your models here.

response_lowongan/models.py
from django.db import models
from halaman_forum.models import Status

# Create your models here.
class Comment(models.Model):
    name = models.TextField(max_length=160, null=True)
    comment = models.TextField(max_length=160)
    created_date = models.DateTimeField(auto_now_add=True)
    status = models.ForeignKey(Status, null=True, blank=True)

    def __str__(self):
        return self.comment

halaman_forum/forms.py
from django import forms

class UpdateStatus_Form(forms.Form):
	error_messages = {
		'required': 'Please enter this input',
		'invalid': 'Isi input ini dengan status',
	}
	attrs = {
		'class': 'form-control',
		'placeholder' : "Start writing your job vacancies!",
		'rows' : 6,
		'cols' : 25
	}

	status = forms.CharField(label='', required=True, max_length=500, widget=forms.Textarea(attrs=attrs))

response_lowongan/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi status',
    }
    description_attrs ={
    	'type':'text',
    	'rows':4,
    	'class':'status-form-textarea',
    	'placeholder':"What's on your mind?"
    }

    #name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    #email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    status = forms.CharField(widget=forms.Textarea(attrs=description_attrs), required=True, label='')


class Comment_Form(forms.Form):
    error_messages ={
        'required':'Tolong isi comment'
    }
    description_attrs ={
        'id':'form-comment',
        'type':'text',
        'rows':1,
        'class':'form-control',
        'placeholder':'Berikan tanggapan Anda'
    }
    comment = forms.CharField(widget=forms.Textarea(attrs=description_attrs), required=True, max_length = 160, label='')

class Name_Form(forms.Form):
    error_messages ={
        'required':'Tolong isi comment'
    }
    description_attrs ={
        'id':'form-name',
        'type':'text',
        'rows':1,
        'class':'form-control',
        'placeholder':'Tuliskan nama Anda'
    }
    name = forms.CharField(widget=forms.Textarea(attrs=description_attrs), required=True, max_length = 100, label='')

halaman_forum/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from halaman_profile.models import AccountProfile
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import Status
from .forms import UpdateStatus_Form

# Create your views here.
response = {'author': 'Kelompok 4 PPW-F'}

def index(request):
    html = 'halaman_forum.html'
    response['company_name'] = request.session.get('company_name')
    response['company_about'] = request.session.get('company_about')
    response['company_type'] = request.session.get('company_type')
    response['company_web'] = request.session.get('company_web')
    response['company_speciality'] = request.session.get('company_speciality')
    response['company_imgURL'] = request.session.get('company_imgURL')
    status = Status.objects.all()
    response['status'] = status
    response['updatestatus_form'] = UpdateStatus_Form
    return render(request, html, response)

def status_post(request):
	form = UpdateStatus_Form(request.POST)
	if request.method == 'POST' and form.is_valid():
		response['status'] = request.POST['status'] #if request.POST['name'] != ""
		status = Status(status=response['status'])
		status.save()
		html = 'halaman_forum.html'
		render(request, html, response)
		return HttpResponseRedirect('/halaman-forum/')
	else:
		return HttpResponseRedirect('/halaman-forum/')
	

halaman_profile/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from .models import AccountProfile
from django.http import HttpResponse

# Create your views here.
response = {'author': 'Kelompok 4 PPW-F'}

def index(request):
    html = 'halaman_profile.html'
    response['company_name'] = request.session.get('company_name')
    response['company_about'] = request.session.get('company_about')
    response['company_type'] = request.session.get('company_type')
    response['company_web'] = request.session.get('company_web')
    response['company_speciality'] = request.session.get('company_speciality')
    response['company_imgURL'] = request.session.get('company_imgURL')
    return render(request, html, response)
	

halaman_utama/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from halaman_forum.models import Status
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from response_lowongan.forms import Name_Form, Comment_Form

# Create your views here.
response = {'author': 'Kelompok 4 PPW-F'}

def index(request):
    html = 'halaman_utama.html'
    response['name_form'] = Name_Form
    response['comment_form'] = Comment_Form
    status_job = Status.objects.all().order_by('-created_date')
    paginator = Paginator(status_job, 3)
    page = request.GET.get('page')
    try:
        forum = paginator.page(page)
    except:
        forum = paginator.page(1)

    response['status'] = forum
    
    return render(request, html, response)

response_lowongan/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from halaman_forum.models import Status
from .models import Comment
from .forms import Name_Form, Comment_Form

# Create your views here.
response = {'author': 'Kelompok 4 PPW-F'}

status_dict ={}

def index(request):
    return HttpResponseRedirect('/halaman-utama/')

def add_comment(request, pk):
	status = Status.objects.get(pk=pk)
	form = Comment_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['comment'] = request.POST['comment']

		comment=Comment(comment=response['comment'])
		comment.status = status
		comment.name = request.POST['name']
		print(comment.name)
		comment.save()
		return redirect('/halaman-utama/')
	else:
		return HttpResponseRedirect('/halaman-utama/')

halaman_forum/templates/halaman_forum.html
{% extends "base.html" %}

{% block content %}
    <section name="status-input" id="status-input">
    	<div>
    		<form id="form" method="POST" action="{% url 'halaman-forum:add_status' %}">
    			<h2 class="text-center">Post your job vacation here!</h2>
    			<br>
    			{% csrf_token %}
    			{{ updatestatus_form.status }}
    			<br>
    			<input id="submit" type="submit" class="btn btn-lg btn-block btn-info center-block" value="Post">
    			<br>
    		</form>
    	</div>
    </section>
	<h3 style="text-align: center; font-family: Open Sans; font-weight: bold;">{{ company_name }}'s Posts</h3>
	<hr>
	<section name="status">
		<div class="container">
			<div class="flex">
				{% if status %}
					{% for data in status reversed %}
						<div class="flex-item">
							<div class="row">
								<div class="col-sm-1"></div>
								<div class="col-sm-1">
									<div class="display-picture">
										<img src="{{ company_imgURL }}" style="border-radius: 50%; display: block; margin: 0 auto" width="70px" height="70px">
									</div>
								</div>
								<div class="col-sm-9">
										<div class="author-name" style="font-family: Open Sans; font-weight: bold;">
											<a href="/halaman-profile/">{{ company_name }}</a>
										</div>
										<div class="status-message">
											{{ data.status }}
										</div>
										<div class="date-created" style="font-family: Open Sans; font-weight: bold;">
											{{ data.created_date }}
										</div>
								</div>
								<div class="col-sm-1"></div>
							</div>
						</div>
					{% endfor %}
				{% else %}
					<div class="empty-message">
						<p style="font-weight: bold; font-size: 20px; margin-left: 20px;">You haven't posted anything. Start to post one!</p>
					</div>
					<br>
				{% endif %}
			</div>
		</div>
	</section>

	<br>
	<br>
	<br>
{% endblock %}

halaman_profile/templates/halaman_profile.html
{% extends "base.html" %}

{% block content %}

<img src="{{ company_imgURL }}" style="border-radius: 50%; display: block; margin: 0 auto" width="200px" height="200px">
<div>
	<h1 id="companyName" align="center" style="font-weight: bold; font-family: Open Sans"><a href="/halaman-profile/edit_profile"><i class="fa fa-cog" aria-hidden="true"></i>
</a></h1>
</div>
<p id="about" align="center" style="font-weight: bold; font-family: Open Sans; font-size: 17px; word-wrap: break-word;"></p>
<hr/>
<section align="center" style="height: auto;">
    <div class="container" >
        <a href="{% url 'halaman-forum:index' %}" class="btn btn-primary">Lihat Forum</a>
        <a class="btn btn-primary">Cari Mahasiswa</a>
    </div>
</section>    

<section name="bio">
    <div class="row" style="margin-top: 15px; font-family: Open Sans">
        <h5 class="col-sm-4"></h5>
        <h5 class="col-sm-2" style=""><b>Tipe Perusahaan</b></h5>
        <h5 id="companyType" class="col-sm-5"></h5>
    </div>
    <div class="row" style="font-family: Open Sans">
        <h5 class="col-sm-4"></h5>
        <h5 class="col-sm-2"><b>Web Perusahaan</b></h5>
        <h5 id="companyWeb" class="col-sm-5"></h5>
    </div>
    <div class="row" style="font-family: Open Sans">
        <h5 class="col-sm-4"></h5>
        <h5 class="col-sm-2"><b>Spesialitas</b></h5>
        <h5 id="companySpecialty" class="col-sm-5"></h5>
    </div>
    <!-- <div class="row" style="font-family: Open Sans">
        <h5 class="col-sm-4"></h5>
        <h5 class="col-sm-2"><b>Email</b></h5>
        <h5 class="col-sm-5">{{ default.email }}</h5>
    </div> -->
</section>
<br>
<br>

{% endblock %}

halaman_utama/templates/halaman_utama.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="text-center">
                <h3>Find Job Information Here!</h3>       
            </div>
            <br>
        </div>
    </div>
</div>
<div class="text-center">
    <script type="in/Login"></script>
</div>

<script type="text/javascript">
    api_key: 81u03qfjmribz9
    authorize: true
    onLoad: onLinkedInLoad
</script>

<script type="text/javascript">
    
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    // Handle the successful return from the API call
    function onSuccess(data) {
        console.log(data);
    }

    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }

    // Use the API call wrapper to request the member's basic profile data
    function getProfileData() {
        IN.API.Raw("/people/~").result(onSuccess).error(onError);
    }

</script>

<!-- Print errors if any -->
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
	<strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
	<strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endif %}

{% block bar %}
{% include "response_lowongan.html" %}
{% endblock %}

<nav>
	{% if status.has_other_pages %}
	<ul class="pagination" style="justify-content: center; margin-top: 20px">
		{% if status.has_previous %}
		<li class="page-item"><a class="page-link" href="?page={{ forum.previous_page_number }}">&laquo;</a></li>
		{% else %}
		<li class="page-item disabled"><span class="page-link">&laquo;</span></li>
		{% endif %}
		{% for i in status.paginator.page_range %}
		{% if status.number == i %}
		<li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
		{% else %}
		<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
		{% endif %}
		{% endfor %}
		{% if status.has_next %}
		<li class="page-item"><a class="page-link" href="?page={{ forum.next_page_number }}">&raquo;</a></li>
		{% else %}
		<li class="page-item disabled"><span class="page-link">&raquo;</span></li>
		{% endif %}
	</ul>
	{% endif %}
</nav>

{% endblock %}

response_lowongan/templates/response_lowongan.html
<div class="container-fluid job-list">
    <h1 class="text-center">Job Forums</h1>
    <div class="flex-list">
        {% if status %}
        {% for i in status  %}
            <div class="flex-list-item friend-list-item">
                <!-- kasih image disini -->
                <div class="flex-list-item-post">
                    <h3>Nama Perusahaan : {{ i.pengguna.nama }}</h3>
                    <h4>{{ i.title }}</h4>
                    <h4>{{ i.status }}</h4>
                    <h5>{{ i.created_date }}</h5>
                </div>
            </div>
            <div class="flex-list-item-comment-section">
                    <div class="comment-section">
                        <div class="comment-section-comment">
                            <h3>Comment</h3>
                            {% if i.comment_set.all %}
                                {% for comment in i.comment_set.all %}
                                    <div class="comment-block">
                                        <h4>{{comment.name}}</h4>
                                        <h5>{{comment.comment}}</h5>
                                        <h6>{{comment.created_date}}</h6>
                                        <hr>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="comment-section-form">
                            <form id="form-add-comment" action="{% url 'response-lowongan:add_comment' pk=i.id %}" method="POST" class="form-comment panel panel-default" style="color: black" >
                                <div class="form-group">
                                    {% csrf_token %}
                                    <label for="form-name" class="col-sm-2 col-form-label">Name</label>
                                    <div class="col-sm-10">
                                        {{ name_form }}
                                    </div>
                                    <label for="form-comment" class="col-sm-2 col-form-label">Tanggapan</label>
                                    <div class="col-sm-10">
                                            {{ comment_form }}
                                    </div>
                                    <div class="input-comment">
                                        <input id="submit" type="submit" class="btn" value="Submit" style="bottom: -10px">
                                    </div>
                                    <br>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            <br>
        {% endfor %}
        {% else %}
        {% endif %}
    </div>
</div>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Tugas 2 PPW">
    <meta name="author" content="{{author}}">
    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Slab" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
        api_key: 81u03qfjmribz9
        onLoad: checkLoggedIn
        authorize: true
    </script>
    <title>
        Tugas 2 PPW by {{author}}
    </title>
</head>
<body>
    <header>
        {% block header %}
            {% include 'partials/header.html' %}
            <!-- Your Header Here -->
        {% endblock %}
    </header>
    <content>
        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </content>
    <footer>
        {% block footer %}
            {% include 'partials/footer.html' %}
            <!-- Your Footer Here -->
            {% endblock %} 
    </footer>
<!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="{% static 'js/profile.js' %}"></script>
</body>
</html>

templates/partials/footer.html
<!--<p class="modal-footer" 
style="
left: 0;
bottom: 0;
width: 100%;
background-color: white;
color: black;
text-align: center;">&copy; Made with Blood, Sweat, &amp; Tears by {{author}}</p>
<!-- <div>
	<p align="center">&copy; Created with blood, sweat, &amp; tears by {{ author }}</p>
</div> -->

templates/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="{% url 'halaman-utama:index' %}">PPW x LinkedIn</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-right">
				<li><a onclick="logout()"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
			</ul>
			<ul class="nav navbar-right">
				<li><a href="{% url 'halaman-profile:index' %}"><i class="fa fa-user" aria-hidden="true"></i> Profile</a></li>
			</ul>
			<ul class="nav navbar-right">
				<li><a href="{% url 'halaman-forum:index' %}">Forum Lowongan</a></li>
			</ul>
		</div>
	</div>
</nav>